### ISSUE TITLE
[feature request] Marry bride

### ISSUE THREAD

**Issue by jeremyckahn** [mcamis/mypolishbride#1]
Hello @mcamis,

Thank you for this excellent project!  I would like to suggest a feature to improve it.  Here's the user story:

> ~As a groom~
> ~I want to marry my polish bride~
> ~So that I can live happily ever after~

> As an American groom named @mcamis living in Chicago, I want to marry my Polish bride who is also currently residing in Chicago so that we can live happily ever after together.

What do you think about the feasibility of implementing this?  I'm happy to work with you on a pull request or provide test cases if that would be helpful!

**Comment by jeremyckahn** [comment]
Yes, that timeline works for me!  It sounds like you've got the implementation handled, but I'd be happy to help facilitate the deploy if you'd like.  I think @mikelse would also be able available to help on that day, in case you need some more support!

**Comment by nopefinenope** [comment]
User story needs refinement just fyi @jeremyckahn. I would suggest something like: 

As an American groom named @mcamis living in Chicago, I want to marry my Polish bride who is also currently residing in Chicago so that we can live happily ever after together.

**Comment by jeremyckahn** [comment]
Good call @nopefinenope! This reduces scope while still delivering the intended benefit to the users. 👍

**Comment by jeremyckahn** [comment]
Looks like this has been deployed, can we close the ticket?

**Comment by mcamis** [comment]
@jeremyckahn Yep! Verified that this is working on prod. Thanks for your help!
